/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host, int first, int second)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;


	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	/* DEBUG */
	add_1_arg.a = first;  // Replace with your desired first number
    add_1_arg.b = second;  // Replace with your desired second number

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
        // Handle the result of the RPC call
        printf("Result of RPC call: %d\n", *result_1);

        // You can add more code to perform actions based on the result
        // For example, you can process the result or take further actions.
    }


	clnt_destroy (clnt);

}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 4) {
		printf ("usage: %s server_host and 2 numbers\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host, atoi(argv[2]), atoi(argv[3]));
exit (0);
}